### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by percymamedy** [JeffreyWay/laravel-elixir-vueify#25]
Hello, am getting the follwing error when I require laravel-elixir-vue in my gulpfile.

"laravel-elixir": "^6.0.0-9",
"laravel-elixir-vue": "^0.1.4",

```
/home/esokia/work/www/my-pimcore-blog/node_modules/laravel-elixir-vue/main.js:3
Elixir.ready(() => {
              ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/esokia/work/www/my-pimcore-blog/gulpfile.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by percymamedy** [comment]
Turned out to be my nodejs version. 

Upgrading to latest version of nodejs v6.3.1 fixed the issue.
