### ISSUE TITLE
Compile Issue on Elixir 5

### ISSUE THREAD

**Issue by agasigp** [JeffreyWay/laravel-elixir-vueify#26]
I'm using elixir 5 and latest laravel-elixir-vueify (1.0.5) I got this error when I run gulp.

```
/var/www/sipd/node_modules/laravel-elixir-vueify/index.js:3
Elixir.ready(() => {
       ^

TypeError: Elixir.ready is not a function
    at Object.<anonymous> (/var/www/sipd/node_modules/laravel-elixir-vueify/index.js:3:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/sipd/gulpfile.js:2:1)

    at Module._compile (module.js:541:32)
```

Is laravel-elixir-vueify not compatible with elixir 5? I see the example in [here](https://github.com/laracasts/Laravel-Elixir-Vueify-Setup/blob/master/package.json), the elixir that you're using is elixir 4.

**Comment by r3oath** [comment]
I am getting this error as well.

**Comment by pascalbaljet** [comment]
Reverting back to 1.0.3 solved it for me.

**Comment by agasigp** [comment]
@pascalbaljet Thanks, it's working now.

**Comment by JeffreyWay** [comment]
Hey everyone - I forgot that a recent commit was actually a breaking change. I've fixed it.

For Elixir 5 and below, pull in @1.0.6, for Elixir 6 and up, just grab the latest @2.0 version.
