### ISSUE TITLE
getting an error

### ISSUE THREAD

**Issue by LasseRafn** [JeffreyWay/laravel-elixir-vueify#28]
```
Elixir.config.js.browserify.transformers.push({
                           ^
```

TypeError: Cannot read property 'transformers' of undefined
    at Elixir.ready (/Users/lasserafn/dev-projects/Conderoo2/node_modules/laravel-elixir-vueify/index.js:4:32)
    at /Users/lasserafn/dev-projects/Conderoo2/node_modules/laravel-elixir/dist/index.js:29:16
    at Array.forEach (native)
    at global.Elixir (/Users/lasserafn/dev-projects/Conderoo2/node_modules/laravel-elixir/dist/index.js:28:24)
    at Object.<anonymous> (/Users/lasserafn/dev-projects/Conderoo2/gulpfile.js:17:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by daviskoko** [comment]
+1

**Comment by daviskoko** [comment]
Fix mine by making sure 

`babel-core\`
`babel-preset-es2015\`
`babel-runtime\`
`babel-plugin-transform-runtime\`

are installed
https://github.com/vuejs/vueify#usage

**Comment by steve-rhodes** [comment]
Have all these installed, but still getting the same error as above when running `gulp`.

Also, what about `require('laravel-elixir-vue-2');` in gulpfile.js? Should we delete that line?
Does `require('laravel-elixir-vueify');` make that redundant?

This is a bit confusing...

**Comment by ayyobro** [comment]
+1
